SELECT
	*
FROM
	portfolio.denver_crime


-- Search for duplicates
SELECT
	INCIDENT_ID,
	COUNT(INCIDENT_ID)
	REPORTED_DATE,
	OFFENSE_CODE,
	OFFENSE_CODE_EXTENSION,
	OFFENSE_TYPE_ID,
	OFFENSE_CATEGORY_ID,
	INCIDENT_ADDRESS
FROM
	portfolio.denver_crime
GROUP BY
	INCIDENT_ID,
	REPORTED_DATE,
	OFFENSE_CODE,
	OFFENSE_CODE_EXTENSION,
	OFFENSE_TYPE_ID,
	OFFENSE_CATEGORY_ID,
	INCIDENT_ADDRESS
HAVING
	COUNT(INCIDENT_ID) > 1;



-- Standardizing REPORTED_DATE

SELECT
	REPORTED_DATE,
	STR_TO_DATE(SUBSTRING_INDEX(REPORTED_DATE, ' ', 1), '%m/%e/%y') AS NEW_DATE,
	SUBSTRING_INDEX(REPORTED_DATE, ' ', - 1)
FROM
	portfolio.denver_crime;


ALTER TABLE portfolio.denver_crime
	ADD COLUMN REPORTED_DATE_ONLY VARCHAR(255),
	ADD COLUMN REPORTED_TIME VARCHAR(255);


UPDATE
	portfolio.denver_crime
SET
	REPORTED_TIME = SUBSTRING_INDEX(REPORTED_DATE, ' ', - 1),
	REPORTED_DATE_ONLY = STR_TO_DATE(SUBSTRING_INDEX(REPORTED_DATE, ' ', 1), '%m/%e/%y');


-- Separate year and month from REPORTED_DATE into individual column

SELECT
	REPORTED_DATE_ONLY,
	SUBSTRING_INDEX(REPORTED_DATE_ONLY, '-', 1),
	SUBSTRING_INDEX(SUBSTRING_INDEX(REPORTED_DATE_ONLY, '-', 2), '-', - 1)
FROM
	portfolio.denver_crime;


ALTER TABLE portfolio.denver_crime
	ADD COLUMN REPORTED_YEAR VARCHAR(255),
	ADD COLUMN REPORTED_MONTH VARCHAR(255);


UPDATE
	portfolio.denver_crime
SET
	REPORTED_YEAR = SUBSTRING_INDEX(REPORTED_DATE_ONLY, '-', 1),
	REPORTED_MONTH = SUBSTRING_INDEX(SUBSTRING_INDEX(REPORTED_DATE_ONLY, '-', 2), '-', - 1);


-- Explore
-- Number crimes per year

SELECT
	REPORTED_YEAR,
	OFFENSE_CATEGORY_ID,
	COUNT(INCIDENT_ID)
FROM
	portfolio.denver_crime
GROUP BY
	REPORTED_YEAR,
	OFFENSE_CATEGORY_ID
ORDER BY
	REPORTED_YEAR DESC



-- Crime by month

SELECT
	REPORTED_MONTH,
	MONTHNAME(REPORTED_DATE_ONLY) AS month_reported,
	OFFENSE_CATEGORY_ID,
	COUNT(INCIDENT_ID)
FROM
	portfolio.denver_crime
-- WHERE OFFENSE_CATEGORY_ID = ''
GROUP BY
	REPORTED_MONTH,
	month_reported,
	OFFENSE_CATEGORY_ID
ORDER BY
	REPORTED_MONTH ASC,
	OFFENSE_CATEGORY_ID ASC;


-- Highest crime count per neighborhood

WITH order_year AS (
	SELECT
		REPORTED_YEAR,
		NEIGHBORHOOD_ID,
		COUNT(INCIDENT_ID) AS NUMBER_CRIMES,
		RANK() OVER (PARTITION BY REPORTED_YEAR ORDER BY COUNT(INCIDENT_ID)
			DESC) AS YEAR_RANK
	FROM
		portfolio.denver_crime
	GROUP BY
		1,
		2 ORDER BY
			1 DESC,
			3 DESC
)
SELECT
	*
FROM
	order_year
WHERE
	YEAR_RANK <= 3;

SELECT
	REPORTED_YEAR,
	NEIGHBORHOOD_ID,
	COUNT(INCIDENT_ID) AS NUMBER_CRIMES,
	RANK() OVER (PARTITION BY REPORTED_YEAR ORDER BY COUNT(INCIDENT_ID)
		DESC) AS YEAR_RANK
FROM
	portfolio.denver_crime
GROUP BY
	1,
	2
ORDER BY
	1 DESC,
	3 DESC;


SELECT
	GEO_LON,
	GEO_LAT,
	INCIDENT_ID,
	OFFENSE_CATEGORY_ID,
	NEIGHBORHOOD_ID,
	REPORTED_YEAR,
	MONTHNAME(REPORTED_DATE_ONLY) AS REPORTED_MONTH1,
	REPORTED_TIME
	-- COUNT(INCIDENT_ID) AS ID
	-- COUNT(DISTINCT(INCIDENT_ID))
FROM
	portfolio.denver_crime
WHERE
	OFFENSE_CATEGORY_ID = 'aggravated-assault'
	OR OFFENSE_CATEGORY_ID = 'arson'
	OR OFFENSE_CATEGORY_ID = 'auto-theft'
	OR OFFENSE_CATEGORY_ID = 'burglary'
	OR OFFENSE_CATEGORY_ID = 'murder'
	OR OFFENSE_CATEGORY_ID = 'robbery'
	OR OFFENSE_CATEGORY_ID = 'sexual-assault'
LIMIT 1000000;

SELECT
	REPORTED_MONTH,
	MONTHNAME(REPORTED_DATE_ONLY)
FROM
	portfolio.denver_crime;
